language: node_js
node_js:
  - "lts/*"
cache: yarn

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
    - os: windows
      cache: false
      node_js:
        - "10.9.0"
        - "lts/*"
